### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by alex3d** [yuhangwang/plot#1]
Does `plot` compatible with python3?
It seems that it doesn't.

```sh
alex3d@share:/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

alex3d@share:/tmp$ pyvenv venv
alex3d@share:/tmp$ . ./venv/bin/activate
(venv) alex3d@share:/tmp$ pip install plot
Collecting plot
  Downloading plot-0.1.4-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 1.0MB/s 
Collecting functools (from plot)
  Downloading functools-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 4, in <module>
        import functools
      File "/tmp/pip-build-aqcjx08u/functools/functools.py", line 34
        raise TypeError, 'compose expects at least one argument'
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aqcjx08u/functools/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv) alex3d@share:/tmp$ pip install --upgrade pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 840kB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-9.0.1

(venv) alex3d@share:/tmp$ pip install plot
Collecting plot
  Using cached plot-0.1.4-py2.py3-none-any.whl
Collecting numpy (from plot)
  Downloading numpy-1.11.2-cp35-cp35m-manylinux1_x86_64.whl (15.6MB)
    100% |████████████████████████████████| 15.6MB 58kB/s 
Collecting functools (from plot)
  Using cached functools-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 4, in <module>
        import functools
      File "/tmp/pip-build-llap49lw/functools/functools.py", line 34
        raise TypeError, 'compose expects at least one argument'
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-llap49lw/functools/
```

**Comment by yuhangwang** [comment]
Yes, `plot` supports Python 3. In fact, I am developing `plot` using python 3.5. 
The problem was in caused by `functools` which I have removed this dependency 
in the latest release `0.1.7`.
Please try again.

**Comment by alex3d** [comment]
Thanks.
